FROM node:20

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable \
       fonts-ipafont-gothic \
       fonts-wqy-zenhei \
       fonts-thai-tlwg \
       fonts-kacst \
       fonts-freefont-ttf \
       libxss1 \
       --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN npm init -y
RUN npm i swagger-ui-express swagger-jsdoc express puppeteer
COPY . .
EXPOSE 8080
CMD ["node", "app.js"]
